title: OSC Database
author:
  name: John Smith
  email: "john.smith@foobar.com"
#description: description text

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  #collections: true
  
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: minima

header_pages:
  - LICENSE.md
 
